/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gym;

import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class adminF extends javax.swing.JFrame {
 int mouseX;
    int mouseY;
            admin_Details admind ;
            User_Details userd;
String userSex="";
String selectedIdNoti="";

String filter_payment="";
String ban = "";
DefaultTableModel tm;
    public adminF(String name) throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        admind = new admin_Details();
        int mcount = admind.get_Total_Users_count();
        int ccount = admind.get_Total_Coaches_count();
        jLabel8.setText("Total Users:"+mcount);
        jLabel11.setText("Total Coaches:"+ccount);
        jLabel10.setText("Total ExpiredMS:"+admind.get_Total_Exms_count());
        jLabel36.setText("Total Banned Users:"+admind.get_Total_Banusers_count());
        jLabel38.setText("Total Notifications:"+admind.get_Total_Notification_count());
        jLabel9.setText("Total Payments:"+admind.get_all_Total_Payments_count());
jLabel12.setText("Welcome:"+name);
int ncount = admind.get_Total_Notification_count();
 tm = (DefaultTableModel)notiTable.getModel();
        for (int i = 1; i <= ncount; i++) {
        tm.addRow( admind.get_notification());
    }
   int pcount = admind.get_all_Total_Payments_count();
 tm = (DefaultTableModel)jTable3.getModel();
        for (int i = 1; i <= pcount; i++) {
        tm.addRow( admind.get_Payments());
    }
        
        tm = (DefaultTableModel)jTable4.getModel();
        for (int i = 1; i <= mcount; i++) {
        tm.addRow( admind.get_members_data());
    }
        tm = (DefaultTableModel)jTable5.getModel();
        for (int i = 1; i <= ccount; i++) {
        tm.addRow( admind.get_couches_data());
    }
        
admind.conclose();
////
 userd = new User_Details("1");
Object []Users = userd.get_allNameForAdmin();
        DefaultComboBoxModel dm = new DefaultComboBoxModel(Users);
        notiComboBox.setModel(dm);
banComboBox.setModel(dm);

        userd.conclose();
    }
   void update_all_information(){
       admind.conclose();
       userd.conclose();
admind = new admin_Details();

       int ncount = admind.get_Total_Notification_count();
       tm = (DefaultTableModel)notiTable.getModel();
        while(tm.getRowCount()>0){
            for (int i = 0; i < tm.getRowCount(); i++) {
                tm.removeRow(i);
            }
        }
        for (int i = 1; i <= ncount; i++) {
        tm.addRow( admind.get_notification());
    }
        admind.conclose();
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        addresstxbox = new javax.swing.JTextField();
        pwtxbox = new javax.swing.JPasswordField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        nametxbox = new javax.swing.JTextField();
        agetxbox = new javax.swing.JFormattedTextField();
        pntxbox = new javax.swing.JFormattedTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        notiTable = new javax.swing.JTable();
        jButton25 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        notiComboBox = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        notiTxBox = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        ppending = new javax.swing.JRadioButton();
        pcomplete = new javax.swing.JRadioButton();
        jButton18 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        unbanRadio = new javax.swing.JRadioButton();
        BanRadio = new javax.swing.JRadioButton();
        banComboBox = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        jButton27 = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1028, 615));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1028, 615));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(248, 158, 44));
        jPanel3.setPreferredSize(new java.awt.Dimension(3, 713));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 713, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 0, 3, 713));

        jPanel2.setBackground(new java.awt.Color(21, 25, 28));

        jButton8.setBackground(new java.awt.Color(248, 158, 44));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setBorderPainted(false);
        jButton8.setLabel("Add Notifcation ");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/Images/Webp.net-resizeimage (5).png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(248, 158, 44));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(203, 203, 203));
        jLabel12.setText("Welcome:..");

        jButton10.setBackground(new java.awt.Color(248, 158, 44));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Total Members");
        jButton10.setBorderPainted(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(248, 158, 44));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setBorderPainted(false);
        jButton11.setLabel("Payment");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(248, 158, 44));
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setBorderPainted(false);
        jButton12.setLabel(" Total Coaches ");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(248, 158, 44));
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setBorderPainted(false);
        jButton13.setLabel("Add Coach ");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(248, 158, 44));
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("Logout");
        jButton14.setBorderPainted(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(248, 158, 44));
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("Home");
        jButton16.setBorderPainted(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton23.setBackground(new java.awt.Color(248, 158, 44));
        jButton23.setForeground(new java.awt.Color(255, 255, 255));
        jButton23.setText("Ban Users");
        jButton23.setBorderPainted(false);
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(22, 22, 22)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        jPanel4.setBackground(new java.awt.Color(21, 25, 28));
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
        });
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(248, 158, 44));
        jPanel8.setPreferredSize(new java.awt.Dimension(733, 4));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 36, 770, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(203, 203, 203));
        jLabel2.setText("Admin Dashboard");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 220, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/Images/icons8_minimize_window_30px_2.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 31, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/Images/icons8_close_window_30px.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 31, 38));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 770, 40));

        jPanel7.setBackground(new java.awt.Color(31, 36, 42));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(new java.awt.Color(255, 102, 51));
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 24, 101, -1));

        jLabel6.setForeground(new java.awt.Color(255, 102, 51));
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 24, 101, -1));

        jLabel7.setForeground(new java.awt.Color(255, 102, 51));
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 24, 101, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(203, 203, 203));
        jLabel8.setText("Total Users:..");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 123, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(203, 203, 203));
        jLabel9.setText("Total Payments:0");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, 220, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(203, 203, 203));
        jLabel10.setText("Total ExpiredMS:...");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 260, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(203, 203, 203));
        jLabel11.setText("Total Coaches:...");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, 20));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(203, 203, 203));
        jLabel36.setText("Total Banned Users:...");
        jPanel7.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 270, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(203, 203, 203));
        jLabel38.setText("Total Notification:...");
        jPanel7.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 260, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/Images/111111111111111111111111111111.png"))); // NOI18N
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/Images/111111111111111111111111111111.png"))); // NOI18N
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/Images/33333333333333.png"))); // NOI18N
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, 150));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/Images/4444444444444.png"))); // NOI18N
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/Images/5555555555555.png"))); // NOI18N
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/Images/66666666666666666666.png"))); // NOI18N
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jTabbedPane2.addTab("tab1", jPanel7);

        jPanel9.setBackground(new java.awt.Color(31, 36, 42));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addresstxbox.setBackground(new java.awt.Color(31, 36, 42));
        addresstxbox.setForeground(new java.awt.Color(204, 204, 204));
        jPanel9.add(addresstxbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 242, 30));

        pwtxbox.setBackground(new java.awt.Color(31, 36, 42));
        pwtxbox.setForeground(new java.awt.Color(204, 204, 204));
        jPanel9.add(pwtxbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 240, 30));

        jRadioButton1.setBackground(new java.awt.Color(31, 36, 42));
        jRadioButton1.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButton1.setText("Male");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel9.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 87, -1));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(248, 158, 44));
        jLabel14.setText("Password:");
        jPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        jRadioButton2.setBackground(new java.awt.Color(31, 36, 42));
        jRadioButton2.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel9.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 87, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/Images/111111111111111111111111111111.png"))); // NOI18N
        jPanel9.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 84, 208, -1));

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(248, 158, 44));
        jLabel16.setText("Address:");
        jPanel9.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));

        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(248, 158, 44));
        jLabel21.setText("Age:");
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, -1));

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(248, 158, 44));
        jLabel17.setText("Pn:");
        jPanel9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(248, 158, 44));
        jLabel18.setText("Name:");
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 254, -1, -1));

        jButton15.setBackground(new java.awt.Color(248, 158, 44));
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("Add Coach");
        jButton15.setBorderPainted(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, 251, 30));

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(248, 158, 44));
        jLabel19.setText("Sex:");
        jPanel9.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, -1, 30));

        nametxbox.setBackground(new java.awt.Color(31, 36, 42));
        nametxbox.setForeground(new java.awt.Color(204, 204, 204));
        jPanel9.add(nametxbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 254, 242, 30));

        agetxbox.setBackground(new java.awt.Color(31, 36, 42));
        agetxbox.setForeground(new java.awt.Color(203, 203, 203));
        try {
            agetxbox.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel9.add(agetxbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 240, 30));

        pntxbox.setBackground(new java.awt.Color(31, 36, 42));
        pntxbox.setForeground(new java.awt.Color(203, 203, 203));
        try {
            pntxbox.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)-####-###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel9.add(pntxbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 392, 240, 30));

        jTabbedPane2.addTab("tab2", jPanel9);

        jPanel11.setBackground(new java.awt.Color(31, 36, 42));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(248, 158, 44));
        jLabel35.setText("Message:");

        jButton21.setBackground(new java.awt.Color(248, 158, 44));
        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setText("Send Notification");
        jButton21.setBorderPainted(false);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        notiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Senter_Name", "Member_Name", "Message", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        notiTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notiTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(notiTable);

        jButton25.setBackground(new java.awt.Color(248, 158, 44));
        jButton25.setForeground(new java.awt.Color(255, 255, 255));
        jButton25.setText("Update Notification");
        jButton25.setBorderPainted(false);
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/Images/icons8_notification_200px.png"))); // NOI18N

        notiComboBox.setForeground(new java.awt.Color(203, 203, 203));
        notiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All" }));
        notiComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notiComboBoxActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(248, 158, 44));
        jLabel34.setText("User:");

        notiTxBox.setBackground(new java.awt.Color(31, 36, 42));
        notiTxBox.setColumns(20);
        notiTxBox.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        notiTxBox.setForeground(new java.awt.Color(203, 203, 203));
        notiTxBox.setLineWrap(true);
        notiTxBox.setRows(5);
        notiTxBox.setText("TypeYourMessage For Your Member Here");
        notiTxBox.setWrapStyleWord(true);
        notiTxBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jScrollPane3.setViewportView(notiTxBox);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(204, 204, 204))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel33))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel34)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(notiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addGap(8, 8, 8)
                .addComponent(jLabel35)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        jTabbedPane2.addTab("tab6", jPanel11);

        jPanel5.setBackground(new java.awt.Color(31, 36, 42));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "m_id", "C_id", "price", "status", "card no", "tran id", "Type m_ship "
            }
        ));
        jScrollPane2.setViewportView(jTable3);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/Images/5555555555555.png"))); // NOI18N

        jButton17.setBackground(new java.awt.Color(248, 158, 44));
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setText("Show Filtered Payment Data");
        jButton17.setActionCommand("Show Filtered Data");
        jButton17.setBorderPainted(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        ppending.setForeground(new java.awt.Color(203, 203, 203));
        ppending.setText("Pending");
        ppending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppendingActionPerformed(evt);
            }
        });

        pcomplete.setForeground(new java.awt.Color(203, 203, 203));
        pcomplete.setText("Completed");
        pcomplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcompleteActionPerformed(evt);
            }
        });

        jButton18.setBackground(new java.awt.Color(248, 158, 44));
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("Show All Payment Data");
        jButton18.setBorderPainted(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(281, 281, 281))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(pcomplete, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(ppending, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pcomplete)
                    .addComponent(ppending))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab4", jPanel5);

        jPanel10.setBackground(new java.awt.Color(31, 36, 42));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "name", "pass", "address", "pn", "sex", "age", "status", "banned", "rdate", "enddate", "expired", "m_type"
            }
        ));
        jScrollPane5.setViewportView(jTable4);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/Images/111111111111111111111111111111.png"))); // NOI18N
        jLabel28.setText("jLabel28");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jTabbedPane2.addTab("tab3", jPanel10);

        jPanel6.setBackground(new java.awt.Color(31, 36, 42));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "name", "pass", "address", "pn", "sex", "age", "status", "banned", "rdate", "enddate", "expired"
            }
        ));
        jScrollPane6.setViewportView(jTable5);

        jPanel6.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 750, 320));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/Images/111111111111111111111111111111.png"))); // NOI18N
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        jTabbedPane2.addTab("tab5", jPanel6);

        jPanel12.setBackground(new java.awt.Color(31, 36, 42));

        unbanRadio.setBackground(new java.awt.Color(31, 36, 42));
        unbanRadio.setForeground(new java.awt.Color(203, 203, 203));
        unbanRadio.setText("UnBan User");
        unbanRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unbanRadioActionPerformed(evt);
            }
        });

        BanRadio.setBackground(new java.awt.Color(31, 36, 42));
        BanRadio.setForeground(new java.awt.Color(203, 203, 203));
        BanRadio.setText("Ban User");
        BanRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BanRadioActionPerformed(evt);
            }
        });

        banComboBox.setForeground(new java.awt.Color(203, 203, 203));
        banComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All" }));
        banComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banComboBoxActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(248, 158, 44));
        jLabel40.setText("User:");

        jButton27.setBackground(new java.awt.Color(248, 158, 44));
        jButton27.setForeground(new java.awt.Color(255, 255, 255));
        jButton27.setText("Ban/UnBan User");
        jButton27.setBorderPainted(false);
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/Images/icons8_denied_300px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(261, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel44)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addGap(37, 37, 37)
                                .addComponent(banComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(unbanRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(BanRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(232, 232, 232))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(221, 221, 221))))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(banComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unbanRadio)
                    .addComponent(BanRadio))
                .addGap(18, 18, 18)
                .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab7", jPanel12);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, -7, 790, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
 System.exit(0);             // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
 setState(JFrame.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
jTabbedPane2.setSelectedIndex(2);    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
      jTabbedPane2.setSelectedIndex(4);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
 jTabbedPane2.setSelectedIndex(3);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
       jTabbedPane2.setSelectedIndex(5);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        jTabbedPane2.setSelectedIndex(1);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
admind.auto_restart();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
userSex = "male";   
jRadioButton2.setSelected(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
userSex = "female";   
jRadioButton1.setSelected(false);      
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        if(!nametxbox.getText().isEmpty()&&!pwtxbox.getText().isEmpty()&&!addresstxbox.getText().isEmpty()&&!pntxbox.getText().isEmpty()&&!agetxbox.getText().isEmpty()&&!userSex.isEmpty()){
            if(pwtxbox.getText().length()>=4){
        userd = new User_Details("1");
        if(!userd.check_userExsistForCoach(nametxbox.getText())){
            userd.conclose();
            admin_Details admind = new admin_Details();
            admind.add_newCoach(nametxbox.getText(),pwtxbox.getText(),addresstxbox.getText(), pntxbox.getText(),userSex,agetxbox.getText());
            String m_name = admind.get_idByName(nametxbox.getText());
            String srdate = String.valueOf(LocalDate.now());
           admind.insert_Notification("admin", nametxbox.getText(), "0", m_name, "Welcome "+nametxbox.getText()+" To our GYM", srdate);
            admind.conclose();
         
        }
        else
        {
            userd.conclose();
            
        }}else{
                JOptionPane.showMessageDialog(null, "The Password must be Bigger than or equal 4");
            }}
        else
        {
            JOptionPane.showMessageDialog(null, "Please check on your inputs");
        }

    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        jTabbedPane2.setSelectedIndex(0);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
if(!(notiTxBox.getText().isEmpty())){
        userd = new User_Details("1");
String m_id =userd.get_idByName((String)notiComboBox.getSelectedItem());
    String srdate = String.valueOf(LocalDate.now());

userd.insert_Notification("admin", (String)notiComboBox.getSelectedItem(),"0", m_id, notiTxBox.getText(), srdate);
 update_all_information();
userd.conclose();

}
    }//GEN-LAST:event_jButton21ActionPerformed

    private void notiTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notiTableMouseClicked
        int index = notiTable.getSelectedRow();
        TableModel model = notiTable.getModel();
        String id = model.getValueAt(index,0).toString();
        String name = model.getValueAt(index,2).toString();
        String msg = model.getValueAt(index,3).toString();
        notiComboBox.setSelectedItem(name);
        notiTxBox.setText(msg);
        selectedIdNoti=id;
        
    }//GEN-LAST:event_notiTableMouseClicked

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
if(!(selectedIdNoti.isEmpty())&&!(notiTxBox.getText().isEmpty())){
        userd = new User_Details("1");
  String m_id=userd.get_idByName((String)notiComboBox.getSelectedItem());
          userd.conclose();
          admind = new admin_Details();
        admind.update_Notification(selectedIdNoti,(String)notiComboBox.getSelectedItem(),m_id,notiTxBox.getText());
        admind.conclose();
        update_all_information();
}
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed

        if(filter_payment.equals("complete")){
              tm = (DefaultTableModel)jTable3.getModel();
        while(tm.getRowCount()>0){
            for (int i = 0; i < tm.getRowCount(); i++) {
                tm.removeRow(i);
            }
        }
admind = new admin_Details();
    int pcount = admind.get_Completed_Payments_count();
        for (int i = 1; i <= pcount; i++) {
        tm.addRow( admind.get_Completed_Payments());
    }
                admind.conclose();

}else if(filter_payment.equals("pending")){
      tm = (DefaultTableModel)jTable3.getModel();
        while(tm.getRowCount()>0){
            for (int i = 0; i < tm.getRowCount(); i++) {
                tm.removeRow(i);
            }
        }
    admind = new admin_Details();
    int pcount = admind.get_Pending_Payments_count();
        for (int i = 1; i <= pcount; i++) {
        tm.addRow( admind.get_Pending_Payments());
    }
                admind.conclose();
}
    }//GEN-LAST:event_jButton17ActionPerformed

    private void pcompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcompleteActionPerformed
ppending.setSelected(false);
filter_payment="complete";
    }//GEN-LAST:event_pcompleteActionPerformed

    private void ppendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppendingActionPerformed
pcomplete.setSelected(false);
filter_payment="pending";        
    }//GEN-LAST:event_ppendingActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        admind = new admin_Details();
        tm = (DefaultTableModel)jTable3.getModel();
        while(tm.getRowCount()>0){
            for (int i = 0; i < tm.getRowCount(); i++) {
                tm.removeRow(i);
            }
        }
        int pcount = admind.get_all_Total_Payments_count();
        for (int i = 1; i <= pcount; i++) {
        tm.addRow( admind.refresh_get_Payments());
    }
        admind.conclose();
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        jTabbedPane2.setSelectedIndex(6);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void unbanRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unbanRadioActionPerformed
        BanRadio.setSelected(false);
        ban="0";
    }//GEN-LAST:event_unbanRadioActionPerformed

    private void BanRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BanRadioActionPerformed
        unbanRadio.setSelected(false);
        ban="1";
    }//GEN-LAST:event_BanRadioActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        if(!(ban.isEmpty())&&!banComboBox.getSelectedItem().equals("admin")){
            admind = new admin_Details();
            admind.ban_User((String)banComboBox.getSelectedItem(),ban);
        }
    }//GEN-LAST:event_jButton27ActionPerformed

    private void banComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_banComboBoxActionPerformed

    private void notiComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notiComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notiComboBoxActionPerformed

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
 mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jPanel4MousePressed

    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged
int kordinatX = evt.getXOnScreen();
int kordinatY = evt.getYOnScreen();

this.setLocation(kordinatX-mouseX, kordinatY-mouseY);
    }//GEN-LAST:event_jPanel4MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(coachF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(coachF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(coachF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(coachF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new adminF("admin").setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(adminF.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BanRadio;
    private javax.swing.JTextField addresstxbox;
    private javax.swing.JFormattedTextField agetxbox;
    private javax.swing.JComboBox<String> banComboBox;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField nametxbox;
    private javax.swing.JComboBox<String> notiComboBox;
    private javax.swing.JTable notiTable;
    private javax.swing.JTextArea notiTxBox;
    private javax.swing.JRadioButton pcomplete;
    private javax.swing.JFormattedTextField pntxbox;
    private javax.swing.JRadioButton ppending;
    private javax.swing.JPasswordField pwtxbox;
    private javax.swing.JRadioButton unbanRadio;
    // End of variables declaration//GEN-END:variables
}
